#!/bin/bash

#если убрать, работать не будет
sleep 10

#enable i2c interface
modprobe i2c-dev

sleep 1
for loop in 1 2 3 4 5
do
    is_1a=$(i2cdetect -y  1 0x1a 0x1a | egrep "(1a|UU)" | awk '{print $2}')

    if [ "x${is_1a}" != "x" ] ; then
        rm /etc/asound.conf
        rm /var/lib/alsa/asound.state

        echo "create wm8960-soundcard configure file"
        ln -s /etc/wm8960-soundcard/asound.conf /etc/asound.conf

        echo "create wm8960-soundcard status file"
        ln -s /etc/wm8960-soundcard/wm8960_asound.state /var/lib/alsa/asound.state
        break
    fi
    sleep 3
done

alsactl restore
